const translations = {
    zh: {
        // --- 通用 UI ---
        title: "GGPoker 手牌分析儀",
        subtitle: "數據驅動決策，洞悉致勝之道",
        upload_title: "上傳牌譜",
        analyze_data: "開始分析",
        download_data: "下載原始數據",
        clear_all: "全部清除",
        loading: "正在分析您的數據...",
        welcome_title: "歡迎使用GGPoker 手牌分析儀",
        welcome_p1: "上傳您的 GGPoker .txt 牌譜文件，即可深入洞察您的遊戲風格、盈利能力與潛在漏洞。",
        upload_click: "點擊或拖曳檔案到此處",
        upload_drag: "支援 .txt, .json 格式",
        upload_supported: "所有數據均在您的瀏覽器本地處理，確保隱私安全。",
        analysis_options: "分析選項",
        uploaded_files: "已上傳的檔案",
        no_files_uploaded: "尚未上傳任何檔案",
        game_type_all: "所有遊戲類型",
        game_type_holdem: "德州撲克",
        game_type_omaha: "奧馬哈",
        error_no_data: "未找到有效的牌譜數據，請檢查文件內容。",
        error_no_data_in_filter: "在此遊戲類型下沒有數據，請嘗試選擇 '所有遊戲類型'。",
        error_generic: "分析過程中發生錯誤，請檢查您的文件或稍後再試。",
        
        // --- 分頁 ---
        tab_overview: "儀表總覽", tab_preflop: "翻前", tab_postflop: "翻後",
        tab_position: "位置", tab_time: "時間", tab_recommendations: "建議", tab_about: "關於",

        // --- 區塊標題 ---
        win_rate_stats: "盈利能力", preflop_style: "翻前風格", postflop_play: "翻後打法",
        session_info: "會話資訊", profit_chart_title: "總營利走勢圖 ($)",
        preflop_open: "翻前開局", preflop_vs_raise: "面對加注", steal_dynamics: "偷盲動態",
        postflop_as_aggressor: "作為翻前攻擊者", postflop_as_caller: "作為翻前跟注者",
        showdown_stats: "攤牌數據", aggression_stats: "各街道攻擊性",
        positional_profit: "各位置盈利能力 (BB/100)",
        positional_style: "各位置遊戲風格", positional_aggression: "各位置 3-Bet 頻率",
        positional_cbet: "各位置 C-Bet 頻率", positional_wtsd: "各位置攤牌率",
        winrate_by_weekday: "按星期分析勝率 (BB/100)", winrate_by_hour: "按小時分析勝率 (BB/100)",
        player_style_radar: "玩家風格雷達圖",

        // --- 數據指標 & 提示 ---
        total_hands: "總手牌", tooltip_total_hands: "分析的總手牌數量。",
        total_profit: "總營利", tooltip_total_profit: "您的總盈利或虧損金額。",
        bb_per_100: "BB/100", tooltip_bb_per_100: "每100手牌的平均盈利（以大盲為單位）。這是衡量您真實勝率的核心指標。",
        profit_bb: "總盈虧(BB)", tooltip_profit_bb: "以大盲注為單位的總盈利或虧損。",
        total_rake: "總水錢", tooltip_total_rake: "您在此會話中貢獻的總水錢金額(包含基本抽水加上Jackpot抽水)。",
        total_profit_with_rake: "總營利 (含水錢)", tooltip_total_profit_with_rake: "您的總營利或虧損金額，包含您贏得的底池和貢獻的水錢。",
        bb_with_rake_per_100: "BB/100 (含水錢)", tooltip_bb_with_rake_per_100: "每100手牌的平均盈利（以大盲為單位），已將水錢計入。這是衡量您真實勝率的核心指標。",
        profit_with_rake_bb: "總盈虧 (含水錢，BB)", tooltip_profit_with_rake_bb: "以大盲注為單位的總盈利或虧損，包含水錢。",
        total_jackpot: "總Jackpot", tooltip_total_jackpot: "您在牌局中累積的 Jackpot 總金額。",
        
        vpip: "VPIP", tooltip_vpip: "自願投錢入池率 (Voluntarily Put in Pot)。衡量您玩牌鬆緊的關鍵指標。理想範圍約在 20-28%。",
        pfr: "PFR", tooltip_pfr: "翻前加注率 (Pre-Flop Raise)。衡量您翻前攻擊性的指標。理想範圍約在 15-23%。",
        limp: "溜入率", tooltip_limp: "在無人加注的情況下，您第一個入池的方式是跟注而非加注的頻率。高水平玩家此數據趨近於0。",

        "3bet": "3Bet PF", tooltip_3bet: "翻前再加注率。面對一個開局加注時，您再加注的頻率。理想範圍約在 7-12%。",
        "4bet": "4Bet PF", tooltip_4bet: "翻前4Bet率。面對一個3-Bet時，您再加注的頻率。",
        fold_vs_3bet: "棄牌給3Bet", tooltip_fold_vs_3bet: "您在開局加注後，面對3-Bet時棄牌的頻率。過高 (>65%) 表示您的開局範圍易受攻擊。",
        fold_vs_4bet: "棄牌給4Bet", tooltip_fold_vs_4bet: "您在3-Bet之後，面對對手4-Bet時棄牌的頻率。",
        cold_call: "冷跟注", tooltip_cold_call: "當您前面有玩家開局加注，而您選擇跟注時的比率。",
        squeeze: "擠壓", tooltip_squeeze: "當有開局加注和至少一個跟注玩家時，您再加注的頻率。",

        steal_attempt: "偷盲率", tooltip_steal_attempt: "您在CO或BTN位置，前面玩家都棄牌時，您開局加注的頻率。理想值應高於 35%。",
        fold_to_steal: "棄牌給偷盲", tooltip_fold_to_steal: "您在盲注位，面對來自CO或BTN的開局加注時，您棄牌的頻率。理想值應低於 75%。",
        
        cbet_flop: "CBet翻牌", tooltip_cbet_flop: "您作為翻前攻擊者，在翻牌圈下注的頻率。理想範圍約在 50-75%。",
        cbet_turn: "CBet轉牌", tooltip_cbet_turn: "在翻牌圈CBet後，您在轉牌圈繼續下注的頻率。",
        cbet_river: "CBet河牌", tooltip_cbet_river: "在轉牌圈CBet後，您在河牌圈繼續下注的頻率。",

        fold_to_cbet_flop: "棄牌給CBet", tooltip_fold_to_cbet_flop: "面臨對手持續下注時，您在翻牌圈棄牌的頻率。過高 (>60%) 表示您在翻後過於輕易放棄。",
        raise_cbet_flop: "加注CBet", tooltip_raise_cbet_flop: "您在翻牌圈面對對手的持續下注時，選擇加注的頻率。",
        check_raise_flop: "過牌-加注", tooltip_check_raise_flop: "您在翻牌圈先過牌，然後在對手下注後再加注的頻率。",
        donk_bet_flop: "領先下注", tooltip_donk_bet_flop: "您在不利位置，搶在翻前攻擊者之前首先下注的頻率。此數據通常應非常低。",
        bet_vs_missed_cbet: "反主動下注", tooltip_bet_vs_missed_cbet: "當翻前攻擊者在翻牌圈過牌時，您下注的頻率。",
        probe_bet_turn: "轉牌探測下注", tooltip_probe_bet_turn: "翻牌圈所有人都過牌後，您在轉牌圈首先下注的頻率。",
        
        wtsd: "攤牌率", tooltip_wtsd: "看到翻牌後，堅持到攤牌的頻率。理想範圍約 25-32%。",
        wtsd_won: "攤牌贏率", tooltip_wtsd_won: "在攤牌時獲勝的頻率。理想值應高於 50%。",
        wwsf: "看到翻牌贏率", tooltip_wwsf: "只要看到翻牌，最終贏得底池的頻率。",
        wtsd_after_cbet: "CBet後攤牌率", tooltip_wtsd_after_cbet: "您在翻牌圈C-Bet之後，最終進到攤牌的頻率。",
        wwsf_as_pfr: "作為PFR的WWSF", tooltip_wwsf_as_pfr: "您作為翻前加注者時，只要看到翻牌就贏得底池的頻率。",
        wwsf_as_caller: "作為跟注者的WWSF", tooltip_wwsf_as_caller: "您作為翻前跟注者時，只要看到翻牌就贏得底池的頻率。",
        
        afq_flop: "AFq翻牌", tooltip_afq_flop: "翻牌圈攻擊頻率: (Bets + Raises) / (Bets + Raises + Calls + Checks)。衡量您翻後攻擊性的指標。",
        afq_turn: "AFq轉牌", tooltip_afq_turn: "轉牌圈攻擊頻率。",
        afq_river: "AFq河牌", tooltip_afq_river: "河牌圈攻擊頻率。",
        preflop_aggression: "翻前攻擊性", tooltip_preflop_aggression: "翻前攻擊指標 (PFR/VPIP)。此數值越高代表您的翻前風格越具攻擊性，較少被動跟注。理想值約在 70-90%。",
        afq_all: "綜合翻後攻擊性", tooltip_afq_all: "綜合翻後攻擊頻率。為翻牌、轉牌、河牌三條街攻擊頻率(AFq)的平均值，綜合衡量您在翻後的整體攻擊性。",
        
        total_duration: "總時長", tooltip_total_duration: "所有獨立遊戲Session的總時長。相鄰牌局間隔超過45分鐘即視為新的Session。",
        hands_per_hour: "手牌/小時", tooltip_hands_per_hour: "平均每小時玩的手牌數量。",
        profit_per_hour: "時薪 ($)", tooltip_profit_per_hour: "以美金計算的平均每小時盈利。",
        profit_with_rake_per_hour: "時薪 (含水錢, $)", tooltip_profit_with_rake_per_hour: "以美金計算的平均每小時盈利，已將水錢計入。",

        tooltip_delete_file: "刪除此檔案",
        
        // --- 優化建議 ---
        rec_title: "📈 您的專屬優化建議",
        rec_good: "表現出色！您的數據顯示出紮實且均衡的策略。繼續保持！",
        rec_limp_high: "🐠 **減少溜入 (Limp)**：溜入是個被動且虧損的打法。嘗試用加注來代替溜入，即使是中等牌力的手牌，這樣能讓你掌握主動權。",
        rec_vpip_high: "🎰 **收緊遊戲範圍 (VPIP)**：您的入池率過高，意味著玩了太多弱牌。請收緊您的起手牌範圍，特別是在前面位置時要更有紀律。",
        rec_vpip_low: "🗿 **放寬遊戲範圍 (VPIP)**：您玩得太緊，可能錯失了很多有利可圖的機會。嘗試在後面位置(CO, BTN)用更寬的範圍來開局和3-Bet。",
        rec_vpip_pfr_gap: "🤔 **提升翻前攻擊性**：VPIP和PFR的差距過大，意味著您跟注太多，打法被動。優秀的玩家更傾向於用加注或棄牌來代替跟注。",
        rec_3bet_low: "💣 **增加 3-Bet 頻率**：您的3-Bet頻率偏低。增加3-Bet不僅能贏得更多死錢，還能孤立弱玩家，並讓您的強牌得到更多價值。",
        rec_4bet_low: "🚀 **建立 4-Bet 威懾**：過低的4-Bet率會讓激進的對手肆無忌憚地3-Bet您。在面對3-Bet時，除了頂級強牌，也應該混入一些詐唬的4-Bet。",
        rec_fold_vs_3bet_high: "🛡️ **加強 3-Bet 防禦**：面對3-Bet時棄牌過多，會讓對手輕易剝削您的開局加注。您需要用一個更平衡的範圍來跟注或4-Bet反擊。",
        rec_steal_low: "🏴‍☠️ **更積極地偷盲**：盲注是桌上的無主寶藏！在CO和BTN位置時，更積極地偷取盲注是穩定盈利的關鍵。您的偷盲率應提升至35%以上。",
        rec_fold_to_steal_high: "💰 **加強盲注防守**：您輕易放棄了太多盲注。面對偷盲，您應該用一個更寬的範圍進行3-Bet或跟注來保衛您的盲注。",
        rec_cbet_low: "📉 **增加持續下注 (C-Bet)**：您在翻前掌握了主動權，但沒有在翻牌圈繼續施壓。在有利的牌面結構上，您應該更頻繁地進行持續下注。",
        rec_cbet_high: "💥 **優化 C-Bet 頻率**：您的持續下注太頻繁了。在多人底池、不利的牌面或面對難纏的對手時，學會用過牌來控制底池，這會讓您更難被預測。",
        rec_fold_to_cbet_high: "✋ **減少對 C-Bet 的棄牌**：對手的C-Bet不總是代表強牌。學會用聽牌、後門聽牌或對子來「漂浮」(Float)對手，或用加注來反擊。",
        rec_wtsd_low: "⏳ **不要過早放棄底池**：您在攤牌前棄牌太頻繁，可能被對手輕易詐唬。請評估底池賠率，用您有攤牌價值的牌跟注到底。",
        rec_wtsd_high_wtsd_won_low: "💸 **避免成為跟注站**：您的攤牌率過高，但攤牌贏率卻很低。這表示您用太多弱牌跟注到底了。學會做出艱難的棄牌，能為您省下大筆資金。",
        rec_afq_low: "🕊️ **提升翻後攻擊性 (AFq)**：您的翻後攻擊頻率偏低，打法過於和平。在有利可圖的時機，多用下注和加注來代替被動的過牌和跟注。",

        // --- About Page (Updated) ---
        about_github_link: "查看 GitHub 專案",
        about_title: "關於本專案",
        about_p1: "與市面上需要複雜設定和訂閱費的專業追蹤軟體（如 PokerTracker, Hold'em Manager）不同，本工具的目標是提供一個<strong>輕量、快速、免費且安全</strong>的替代方案。我們專注於<strong>網頁體驗</strong>，讓您不需要安裝任何軟體，只需打開瀏覽器，無論是在電腦前還是在移動裝置上，都能隨時隨地快速覆盤，找到自己的優勢與待改進之處。",
        report_strengths_title: "優勢 (Strengths)",
        report_strength1: "<strong>完全免費且開源：</strong> 無任何使用成本，程式碼透明，具備高度信任感。",
        report_strength2: "<strong>高度隱私保護：</strong> 所有運算均在使用者本機端完成，手牌數據不經過任何伺服器，無數據外洩風險。",
        report_strength3: "<strong>跨平台、免安裝：</strong> 只需要瀏覽器即可運作，方便在任何裝置上使用。",
        report_strength4: "<strong>數據可攜與累積：</strong> 分析結果可匯出成 JSON 檔案，方便使用者自行備份，並可在下次合併分析，實現長期數據追蹤。",
        report_strength5: "<strong>直觀的數據視覺化：</strong> 提供圖表化呈現，比單純閱讀文字檔更易於理解自己的表現趨勢。",
        report_weaknesses_title: "挑戰 (Challenges)",
        report_weakness1: "<strong>無即時 HUD 功能：</strong> 與專業軟體相比，無法在牌桌上即時顯示對手數據。",
        report_weakness2: "<strong>依賴手動上傳：</strong> 需要手動從 GGPoker 客戶端導出紀錄並上傳，操作上不如自動匯入的軟體便利。",
        report_weakness3: "<strong>數據維度較基礎：</strong> 目前提供的數據指標雖然核心，但與專業軟體相比仍不夠細緻 (例如：缺少特定牌型組合的獲利分析)。",
        report_weakness4: "<strong>前端計算效能瓶頸：</strong> 當手牌數量達到數十萬級別時，純前端 JavaScript 計算可能遇到效能瓶頸。",
        report_weakness5: "<strong>缺乏對手分析功能：</strong> 工具完全聚焦在使用者 (Hero) 本身的數據，無法建立對手資料庫進行針對性分析。",
        report_future_title: "未來藍圖 (Future Roadmap)",
        report_future1: "<strong>雲端後端整合：</strong> 將計算密集型的解析與統計工作移至後端，解決前端效能瓶頸。",
        report_future2: "<strong>使用者帳號系統：</strong> 引入帳號系統，讓使用者可以將分析結果自動儲存於雲端，實現跨裝置數據同步。",
        report_future3: "<strong>手牌視覺化重播：</strong> 點擊單一手牌紀錄，以圖形介面重播該手牌的完整過程。",
        report_future4: "<strong>進階數據篩選器：</strong> 允許使用者根據位置、起手牌、牌局結果等多維度篩選數據。",
        report_future5: "<strong>起手牌矩陣熱圖：</strong> 以 13x13 的矩陣圖顯示所有起手牌的 VPIP、PFR、獲利等數據。",
        report_future6: "<strong>特定賽事/盲注分析：</strong> 增加篩選功能，可只分析特定盲注等級或賽事類型 (如 Rush & Cash)。",
        report_future7: "<strong>更豐富的圖表類型：</strong> 增加圓餅圖 (行動分佈)、雷達圖 (玩家風格評估) 等。",
        report_future8: "<strong>簡易對手數據標記：</strong> 允許使用者在分析時，針對特定對手 ID 加上標籤 (如：魚、緊兇)。",
        report_future9: "<strong>目標導向學習模組：</strong> 根據數據弱點，自動推薦相關的撲克學習資源或文章連結。",
        report_future10: "<strong>社群分享報告：</strong> 產生一個可分享的唯讀報告頁面連結，方便與教練或朋友討論數據。",
    },
    en: {
        // --- General UI ---
        title: "GGPoker Hand Analyzer",
        subtitle: "Data-Driven Decisions, Insights to Victory",
        upload_title: "Upload Hand History",
        analyze_data: "Start Analysis",
        download_data: "Download Raw Data",
        clear_all: "Clear All",
        loading: "Analyzing your data...",
        welcome_title: "Welcome to GGPoker Hand Analyzer",
        welcome_p1: "Upload your GGPoker .txt hand history files to get deep insights into your play style, profitability, and potential leaks.",
        upload_click: "Click or drag file to this area to upload",
        upload_drag: "Supports .txt, .json formats",
        upload_supported: "All data is processed locally in your browser for your privacy.",
        analysis_options: "Analysis Options",
        uploaded_files: "Uploaded Files",
        no_files_uploaded: "No files uploaded yet",
        game_type_all: "All Game Types",
        game_type_holdem: "Hold'em",
        game_type_omaha: "Omaha",
        error_no_data: "No valid hand history data found. Please check the file content.",
        error_no_data_in_filter: "No data available for this game type. Try selecting 'All Game Types'.",
        error_generic: "An error occurred during analysis. Please check your files or try again later.",
        
        // --- Tabs ---
        tab_overview: "Dashboard", tab_preflop: "Preflop", tab_postflop: "Postflop",
        tab_position: "Position", tab_time: "Time", tab_recommendations: "Recommendations", tab_about: "About",

        // --- Block Titles ---
        win_rate_stats: "Profitability", preflop_style: "Preflop Style", postflop_play: "Postflop Play",
        session_info: "Session Info", profit_chart_title: "Total Profit Chart ($)",
        preflop_open: "Preflop Open", preflop_vs_raise: "Vs. Raise", steal_dynamics: "Steal Dynamics",
        postflop_as_aggressor: "As Preflop Aggressor", postflop_as_caller: "As Preflop Caller",
        showdown_stats: "Showdown Stats", aggression_stats: "Aggression by Street",
        positional_profit: "Positional Profitability (BB/100)",
        positional_style: "Positional Play Style", positional_aggression: "Positional 3-Bet Freq.",
        positional_cbet: "Positional C-Bet Freq.", positional_wtsd: "Positional WTSD %",
        winrate_by_weekday: "Win Rate by Day of the Week (BB/100)", winrate_by_hour: "Win Rate by Hour (BB/100)",
        player_style_radar: "Player Style Radar Chart",


        // --- Metrics & Tooltips ---
        total_hands: "Total Hands", tooltip_total_hands: "The total number of hands analyzed.",
        total_profit: "Total Profit", tooltip_total_profit: "Your total profit or loss amount.",
        bb_per_100: "BB/100", tooltip_bb_per_100: "Average profit per 100 hands in big blinds. This is a core metric for your true win rate.",
        profit_bb: "Total Profit (BB)", tooltip_profit_bb: "Total profit or loss in terms of big blinds.",
        total_rake: "Total Rake", tooltip_total_rake: "The total amount of rake you contributed(w/ Rake & Jackpot).",
        total_profit_with_rake: "Total Profit (w/ Rake)", tooltip_total_profit_with_rake: "Your total profit or loss, including pots won and rake contributed.",
        bb_with_rake_per_100: "BB/100 (w/ Rake)", tooltip_bb_with_rake_per_100: "Average profit per 100 hands in big blinds, with rake considered. This is a core metric for your true win rate.",
        profit_with_rake_bb: "Total Profit (w/ Rake, BB)", tooltip_profit_with_rake_bb: "Your total profit or loss in big blinds, including rake.",
        total_jackpot: "Total Jackpot", tooltip_total_jackpot: "The total jackpot amount you've accumulated in your hands.",
        
        vpip: "VPIP", tooltip_vpip: "Voluntarily Put in Pot. Measures how loose/tight you play. Ideal range is around 20-28%.",
        pfr: "PFR", tooltip_pfr: "Pre-Flop Raise. Measures your preflop aggression. Ideal range is around 15-23%.",
        limp: "Limp %", tooltip_limp: "Frequency of entering the pot by calling instead of raising. High-level players have this stat close to 0.",

        "3bet": "3Bet PF", tooltip_3bet: "Preflop 3-Bet percentage. Frequency of re-raising an open-raise. Ideal range is around 7-12%.",
        "4bet": "4Bet PF", tooltip_4bet: "Preflop 4-Bet percentage. Frequency of re-raising a 3-bet.",
        fold_vs_3bet: "Fold to 3-Bet", tooltip_fold_vs_3bet: "Frequency of folding to a 3-bet after you open-raised. Too high (>65%) is exploitable.",
        fold_vs_4bet: "Fold to 4-Bet", tooltip_fold_vs_4bet: "Frequency of folding to a 4-bet after you have 3-bet.",
        cold_call: "Cold Call", tooltip_cold_call: "Frequency of calling a raise when you haven't yet invested money in the pot.",
        squeeze: "Squeeze", tooltip_squeeze: "Frequency of re-raising when there has been a raise and one or more callers before you.",

        steal_attempt: "Steal Attempt", tooltip_steal_attempt: "Frequency of open-raising from CO or BTN. Should be above 35%.",
        fold_to_steal: "Fold to Steal", tooltip_fold_to_steal: "Frequency of folding from the blinds to a steal attempt. Should be below 75%.",
        
        cbet_flop: "C-Bet Flop", tooltip_cbet_flop: "Continuation Bet on the flop as the preflop aggressor. Ideal range is 50-75%.",
        cbet_turn: "C-Bet Turn", tooltip_cbet_turn: "Continuation Bet on the turn after c-betting the flop.",
        cbet_river: "C-Bet River", tooltip_cbet_river: "Continuation Bet on the river after c-betting the turn.",

        fold_to_cbet_flop: "Fold to C-Bet", tooltip_fold_to_cbet_flop: "Frequency of folding to a flop C-Bet. Too high (>60%) means you're over-folding postflop.",
        raise_cbet_flop: "Raise C-Bet", tooltip_raise_cbet_flop: "Frequency of raising versus an opponent's continuation bet on the flop.",
        check_raise_flop: "Check-Raise", tooltip_check_raise_flop: "Frequency of checking then raising an opponent's bet on the flop.",
        donk_bet_flop: "Donk Bet", tooltip_donk_bet_flop: "Frequency of betting out of position before the preflop aggressor has acted. Should be very low.",
        bet_vs_missed_cbet: "Bet vs Missed C-Bet", tooltip_bet_vs_missed_cbet: "Frequency of betting when the preflop aggressor checks back on the flop.",
        probe_bet_turn: "Probe Bet Turn", tooltip_probe_bet_turn: "Frequency of betting on the turn when the flop was checked through.",
        
        wtsd: "WTSD", tooltip_wtsd: "Went To Showdown. Frequency of reaching showdown after seeing the flop. Ideal range is 25-32%.",
        wtsd_won: "W$SD", tooltip_wtsd_won: "Won at Showdown. Frequency of winning the pot at showdown. Should be above 50%.",
        wwsf: "WWSF", tooltip_wwsf: "Won When Saw Flop. Frequency of winning the pot anytime after seeing the flop.",
        wtsd_after_cbet: "WTSD After C-Bet", tooltip_wtsd_after_cbet: "Frequency of going to showdown after you make a continuation bet on the flop.",
        wwsf_as_pfr: "WWSF as PFR", tooltip_wwsf_as_pfr: "Won When Saw Flop frequency when you were the pre-flop aggressor.",
        wwsf_as_caller: "WWSF as Caller", tooltip_wwsf_as_caller: "Won When Saw Flop frequency when you were a pre-flop caller.",
        
        afq_flop: "AFq Flop", tooltip_afq_flop: "Aggression Frequency on the Flop: (Bets + Raises) / (Bets + Raises + Calls + Checks).",
        afq_turn: "AFq Turn", tooltip_afq_turn: "Aggression Frequency on the Turn.",
        afq_river: "AFq River", tooltip_afq_river: "Aggression Frequency on the River.",
        preflop_aggression: "Preflop Aggression", tooltip_preflop_aggression: "Preflop Aggression Factor (PFR/VPIP). A higher value indicates a more aggressive preflop style with less passive calling. An ideal value is around 70-90%.",
        afq_all: "Overall Post-flop Aggression", tooltip_afq_all: "Overall Postflop Aggression. The average of Aggression Frequency (AFq) across the flop, turn, and river, measuring your overall postflop aggressiveness.",
        
        total_duration: "Total Duration", tooltip_total_duration: "Total duration of all sessions. A new session starts after a 45-minute break.",
        hands_per_hour: "Hands/Hour", tooltip_hands_per_hour: "Average number of hands played per hour.",
        profit_per_hour: "Profit/Hour ($)", tooltip_profit_per_hour: "Average profit per hour in USD.",
        profit_with_rake_per_hour: "Profit/Hour (w/ Rake, $)", tooltip_profit_with_rake_per_hour: "Average profit per hour in USD, with rake considered.",

        tooltip_delete_file: "Delete this file",

        // --- Recommendations ---
        rec_title: "📈 Your Personalized Recommendations",
        rec_good: "Excellent Play! Your stats show a solid and balanced strategy. Keep it up!",
        rec_limp_high: "🐠 **Reduce Limping**: Limping is a passive and generally losing play. Try replacing limps with raises to take control of the pot.",
        rec_vpip_high: "🎰 **Tighten Your Range (VPIP)**: Your VPIP is too high, meaning you're playing too many weak hands. Tighten your starting hand selection, especially from early positions.",
        rec_vpip_low: "🗿 **Loosen Your Range (VPIP)**: You're playing too tight and may be missing profitable opportunities. Try opening up your range, especially from late positions (CO, BTN).",
        rec_vpip_pfr_gap: "🤔 **Increase Preflop Aggression**: A large gap between VPIP and PFR indicates passive play (too much calling). Profitable players prefer to either raise or fold preflop.",
        rec_3bet_low: "💣 **Increase 3-Bet Frequency**: Your 3-bet frequency is low. 3-betting more often wins dead money, isolates weaker players, and gets more value for your strong hands.",
        rec_4bet_low: "🚀 **Establish a 4-Bet Threat**: A low 4-bet rate allows aggressive opponents to 3-bet you relentlessly. You should be 4-betting a balanced range of value and bluffs.",
        rec_fold_vs_3bet_high: "🛡️ **Defend Against 3-Bets More**: You're folding too much to 3-bets, which makes your opens easily exploitable. You need to defend by calling and 4-betting with a wider, balanced range.",
        rec_steal_low: "🏴‍☠️ **Steal More Blinds**: The blinds are free money on the table! Stealing them aggressively from the CO and BTN is crucial for your win rate. Aim for over 35%.",
        rec_fold_to_steal_high: "💰 **Defend Your Blinds More**: You are giving up your blinds too easily. You should defend your blinds against steals more often with 3-bets and calls.",
        rec_cbet_low: "📉 **Increase C-Bet Frequency**: You're taking initiative preflop but not following through. You should be continuation betting more frequently on favorable board textures.",
        rec_cbet_high: "💥 **Optimize C-Bet Frequency**: You are c-betting too often. Learn to check-back on wet boards, in multi-way pots, or against tough opponents to make your game less predictable.",
        rec_fold_to_cbet_high: "✋ **Fold Less to C-Bets**: Opponents' c-bets aren't always strong. Learn to 'float' their bets with draws or pairs, or even raise as a bluff to counter-attack.",
        rec_wtsd_low: "⏳ **Don't Give Up Pots Too Early**: You are folding before showdown too often and can be bluffed easily. Consider pot odds and your hand's equity to make better calls.",
        rec_wtsd_high_wtsd_won_low: "💸 **Avoid Being a Calling Station**: Your WTSD is high, but your W$SD is low. This indicates you're calling down with too many weak hands. Learn to make tough folds to save money.",
        rec_afq_low: "🕊️ **Increase Postflop Aggression (AFq)**: Your postflop aggression is low. Look for more opportunities to bet and raise instead of passively checking and calling.",

        // --- About Page (Updated) ---
        about_github_link: "View Project on GitHub",
        about_title: "About This Project",
        about_p1: "Unlike professional tracking software like PokerTracker or Hold'em Manager, which require complex setups and subscriptions, this tool aims to be a <strong>lightweight, fast, free, and secure</strong> alternative. We focus on the <strong>web experience</strong>, so you don't need to install anything. Just open your browser—on your desktop or mobile device—to quickly review your sessions anytime, anywhere, and find your edge.",
        report_strengths_title: "Strengths",
        report_strength1: "<strong>Completely Free & Open-Source:</strong> No costs involved. The code is transparent and trustworthy.",
        report_strength2: "<strong>High Privacy Protection:</strong> All computations are done locally on your device. Hand data never touches a server, eliminating the risk of data leaks.",
        report_strength3: "<strong>Cross-Platform & No Installation:</strong> Works in any modern browser, making it accessible on any device.",
        report_strength4: "<strong>Data Portability & Accumulation:</strong> Analysis results can be exported as a JSON file for personal backup and can be re-imported to merge with new sessions for long-term tracking.",
        report_strength5: "<strong>Intuitive Visualization:</strong> Charts and graphs make it easier to understand your performance trends than reading raw text files.",
        report_weaknesses_title: "Challenges",
        report_weakness1: "<strong>No Real-time HUD:</strong> Unlike professional software, it cannot display opponent stats on the table in real-time.",
        report_weakness2: "<strong>Manual Upload Required:</strong> You need to manually export hand histories from the GGPoker client and upload them.",
        report_weakness3: "<strong>Basic Metrics:</strong> While covering core stats, the level of detail is less granular than professional tools (e.g., no profit analysis by specific holdings).",
        report_weakness4: "<strong>Frontend Performance Bottleneck:</strong> With hundreds of thousands of hands, client-side JavaScript calculation might slow down or cause the browser to lag.",
        report_weakness5: "<strong>No Opponent Analysis:</strong> The tool is entirely focused on 'Hero's' data and does not build a database for analyzing specific opponents.",
        report_future_title: "Future Roadmap",
        report_future1: "<strong>Cloud Backend Integration:</strong> Move computation-heavy tasks to a backend service to resolve frontend performance issues.",
        report_future2: "<strong>User Accounts & Data Sync:</strong> Introduce user accounts to automatically save analysis results to the cloud, enabling cross-device data synchronization.",
        report_future3: "<strong>Visual Hand Replayer:</strong> Add a feature to replay a selected hand graphically from start to finish.",
        report_future4: "<strong>Advanced Data Filters:</strong> Allow users to filter data by position, starting hands, pot size, and more for deeper analysis.",
        report_future5: "<strong>Starting Hand Matrix Heatmap:</strong> Display VPIP, PFR, and profit data for all starting hands on a 13x13 grid.",
        report_future6: "<strong>Specific Game/Stake Analysis:</strong> Add filters for specific stake levels or game types (e.g., Rush & Cash).",
        report_future7: "<strong>More Chart Types:</strong> Introduce pie charts (e.g., action distribution by position) and radar charts (for a holistic view of a player's style).",
        report_future8: "<strong>Simple Opponent Tagging:</strong> While not a full HUD, allow users to add tags (e.g., Fish, TAG) to opponent IDs during review.",
        report_future9: "<strong>Goal-Oriented Learning Modules:</strong> Recommend relevant poker learning resources based on identified statistical weaknesses.",
        report_future10: "<strong>Shareable Reports:</strong> Generate a shareable, read-only link to a report page (excluding sensitive details) for discussions with coaches or friends.",
    },
    ja: {
        // --- 通用 UI ---
        title: "GGPoker ハンドアナライザー",
        subtitle: "データ駆動の意思決定、勝利への洞察",
        upload_title: "ハンド履歴のアップロード",
        analyze_data: "分析を開始",
        download_data: "生データのダウンロード",
        clear_all: "すべてクリア",
        loading: "データを分析中...",
        welcome_title: "GGPoker ハンドアナライザーへようこそ",
        welcome_p1: "GGPokerの.txtハンド履歴ファイルをアップロードして、プレイスタイル、収益性、潜在的なリーク（弱点）を深く分析しましょう。",
        upload_click: "クリックまたはファイルをここにドラッグしてアップロード",
        upload_drag: ".txt, .json形式に対応",
        upload_supported: "すべてのデータはプライバシー保護のため、ブラウザでローカルに処理されます。",
        analysis_options: "分析オプション",
        uploaded_files: "アップロードされたファイル",
        no_files_uploaded: "まだファイルがアップロードされていません",
        game_type_all: "すべてのゲームタイプ",
        game_type_holdem: "ホールデム",
        game_type_omaha: "オマハ",
        error_no_data: "有効なハンド履歴データが見つかりませんでした。ファイル内容を確認してください。",
        error_no_data_in_filter: "このゲームタイプにはデータがありません。「すべてのゲームタイプ」を選択してみてください。",
        error_generic: "分析中にエラーが発生しました。ファイルを確認するか、後でもう一度お試しください。",
        
        // --- 分頁 ---
        tab_overview: "ダッシュボード", tab_preflop: "プリフロップ", tab_postflop: "ポストフロップ",
        tab_position: "ポジション", tab_time: "時間", tab_recommendations: "推奨事項", tab_about: "このプロジェクトについて",

        // --- 區塊標題 ---
        win_rate_stats: "収益性", preflop_style: "プリフロップスタイル", postflop_play: "ポストフロッププレイ",
        session_info: "セッション情報", profit_chart_title: "合計利益チャート ($)",
        preflop_open: "プリフロップオープン", preflop_vs_raise: "レイズに対して", steal_dynamics: "スティールダイナミクス",
        postflop_as_aggressor: "プリフロップアグレッサーとして", postflop_as_caller: "プリフロップコーラーとして",
        showdown_stats: "ショーダウン統計", aggression_stats: "ストリートごとのアグレッション",
        positional_profit: "ポジション別収益性 (BB/100)",
        positional_style: "ポジション別プレイスタイル", positional_aggression: "ポジション別3ベット頻度",
        positional_cbet: "ポジション別C-Bet頻度", positional_wtsd: "ポジション別ショーダウン率", 
        winrate_by_weekday: "曜日別勝率 (BB/100)", winrate_by_hour: "時間別勝率 (BB/100)",
        player_style_radar: "プレイヤースタイルレーダーチャート",

        // --- 數據指標 & 提示 ---
        total_hands: "合計ハンド数", tooltip_total_hands: "分析されたハンドの総数。",
        total_profit: "合計利益", tooltip_total_profit: "あなたの合計利益または損失額。",
        bb_per_100: "BB/100", tooltip_bb_per_100: "100ハンドあたりの平均利益（ビッグブラインド単位）。これはあなたの真の勝率を示すコア指標です。",
        profit_bb: "合計利益 (BB)", tooltip_profit_bb: "ビッグブラインド単位での合計利益または損失。",
        total_rake: "合計レーキ", tooltip_total_rake: "このセッションであなたが貢献した合計レーキ額（通常レーキ＋ジャックポット）。",
        total_profit_with_rake: "合計利益 (レーキ込み)", tooltip_total_profit_with_rake: "あなたの合計利益または損失額で、ポットで勝った金額と貢献したレーキを含みます。",
        bb_with_rake_per_100: "BB/100 (レーキ込み)", tooltip_bb_with_rake_per_100: "100ハンドあたりの平均利益（ビッグブラインド単位）で、レーキを考慮に入れています。これはあなたの真の勝率を示すコア指標です。",
        profit_with_rake_bb: "合計利益 (レーキ込み, BB)", tooltip_profit_with_rake_bb: "ビッグブラインド単位での合計利益または損失で、レーキを含みます。",
        total_jackpot: "合計ジャックポット", tooltip_total_jackpot: "ハンドで積み立てられた合計ジャックポット額。",
        
        vpip: "VPIP", tooltip_vpip: "Voluntarily Put in Pot。どれだけルーズ/タイトにプレイするかを測る指標。理想的な範囲は20〜28%です。",
        pfr: "PFR", tooltip_pfr: "Pre-Flop Raise。プリフロップでのアグレッシブさを測る指標。理想的な範囲は15〜23%です。",
        limp: "リンプ率", tooltip_limp: "誰もレイズしていない状態で、最初にコールで参加する頻度。高レベルプレイヤーはこのスタッツが0に近いです。",

        "3bet": "3Bet PF", tooltip_3bet: "プリフロップ3ベット率。オープンレイズに対してリレイズする頻度。理想的な範囲は7〜12%です。",
        "4bet": "4Bet PF", tooltip_4bet: "プリフロップ4ベット率。3ベットに対してリレイズする頻度。",
        fold_vs_3bet: "3ベットに対するフォールド", tooltip_fold_vs_3bet: "オープンレイズ後、3ベットに対してフォールドする頻度。高すぎる（>65%）とオープンレンジが搾取されやすくなります。",
        fold_vs_4bet: "4ベットに対するフォールド", tooltip_fold_vs_4bet: "3ベット後、相手の4ベットに対してフォールドする頻度。",
        cold_call: "コールドコール", tooltip_cold_call: "まだポットに投資していない状態で、レイズに対してコールする頻度。",
        squeeze: "スクイーズ", tooltip_squeeze: "レイズと1人以上のコーラーがいた場合に、リレイズする頻度。",

        steal_attempt: "スティールアテンプト", tooltip_steal_attempt: "COまたはBTNから、前のプレイヤーが全員フォールドした状態でオープンレイズする頻度。35%以上が理想です。",
        fold_to_steal: "スティールに対するフォールド", tooltip_fold_to_steal: "ブラインドから、COまたはBTNからのオープンレイズに対してフォールドする頻度。75%以下が理想です。",
        
        cbet_flop: "C-Betフロップ", tooltip_cbet_flop: "プリフロップアグレッサーとして、フロップでベットを続ける（コンティニュエーションベット）頻度。理想的な範囲は50〜75%です。",
        cbet_turn: "C-Betターン", tooltip_cbet_turn: "フロップでC-Betした後、ターンでベットを続ける頻度。",
        cbet_river: "C-Betリバー", tooltip_cbet_river: "ターンでC-Betした後、リバーでベットを続ける頻度。",

        fold_to_cbet_flop: "C-Betに対するフォールド", tooltip_fold_to_cbet_flop: "相手のコンティニュエーションベットに対して、フロップでフォールドする頻度。高すぎる（>60%）とポストフロップで降りすぎていることになります。",
        raise_cbet_flop: "C-Betに対するレイズ", tooltip_raise_cbet_flop: "相手のコンティニュエーションベットに対して、フロップでレイズする頻度。",
        check_raise_flop: "チェックレイズ", tooltip_check_raise_flop: "フロップで最初にチェックし、相手のベットに対してレイズする頻度。",
        donk_bet_flop: "ドンクベット", tooltip_donk_bet_flop: "ポジションが悪くても、プリフロップアグレッサーより先にベットする頻度。このスタッツは非常に低いことが望ましいです。",
        bet_vs_missed_cbet: "C-Betミスに対するベット", tooltip_bet_vs_missed_cbet: "プリフロップアグレッサーがフロップでチェックバックしたときに、あなたがベットする頻度。",
        probe_bet_turn: "プローブベットターン", tooltip_probe_bet_turn: "フロップが全員チェックで回った後、ターンで最初にベットする頻度。",
        
        wtsd: "WTSD", tooltip_wtsd: "Went To Showdown（ショーダウンに進んだ）。フロップを見た後、ショーダウンまで進む頻度。理想的な範囲は25〜32%です。",
        wtsd_won: "W$SD", tooltip_wtsd_won: "Won at Showdown（ショーダウンで勝った）。ショーダウンでポットを獲得する頻度。50%以上が理想です。",
        wwsf: "WWSF", tooltip_wwsf: "Won When Saw Flop（フロップを見て勝った）。フロップを見た後に最終的にポットを獲得する頻度。",
        wtsd_after_cbet: "C-Bet後のWTSD", tooltip_wtsd_after_cbet: "フロップでコンティニュエーションベットした後、最終的にショーダウンに進む頻度。",
        wwsf_as_pfr: "PFRとしてのWWSF", tooltip_wwsf_as_pfr: "プリフロップアグレッサーだった場合に、フロップを見た後にポットを獲得する頻度。",
        wwsf_as_caller: "コーラーとしてのWWSF", tooltip_wwsf_as_caller: "プリフロップコーラーだった場合に、フロップを見た後にポットを獲得する頻度。",
        
        afq_flop: "AFqフロップ", tooltip_afq_flop: "フロップでのアグレッション頻度: (ベット数 + レイズ数) / (ベット数 + レイズ数 + コール数 + チェック数)。",
        afq_turn: "AFqターン", tooltip_afq_turn: "ターンでのアグレッション頻度。",
        afq_river: "AFqリバー", tooltip_afq_river: "リバーでのアグレッション頻度。",
        preflop_aggression: "プリフロップアグレッション", tooltip_preflop_aggression: "プリフロップアグレッション指標 (PFR/VPIP)。この数値が高いほど、プリフロップでのスタイルがより攻撃的で、受動的なコールが少ないことを示します。理想値は約70〜90%です。",
        afq_all: "総合ポストフロップアグレッション", tooltip_afq_all: "総合ポストフロップアグレッション頻度。フロップ、ターン、リバーの3つのストリートでのアグレッション頻度(AFq)の平均値で、ポストフロップでの全体的な攻撃性を総合的に測定します。",
        
        total_duration: "合計時間", tooltip_total_duration: "すべての独立したゲームセッションの合計時間。45分以上間隔が空くと新しいセッションと見なされます。",
        hands_per_hour: "ハンド数/時間", tooltip_hands_per_hour: "1時間あたりにプレイした平均ハンド数。",
        profit_per_hour: "時給 ($)", tooltip_profit_per_hour: "1時間あたりの平均利益（米ドル単位）。",
        profit_with_rake_per_hour: "時給 (レーキ込み, $)", tooltip_profit_with_rake_per_hour: "1時間あたりの平均利益（米ドル単位）で、レーキを考慮に入れています。",

        tooltip_delete_file: "このファイルを削除",
        
        // --- 推奨事項 ---
        rec_title: "📈 あなたのパーソナライズされた推奨事項",
        rec_good: "素晴らしいプレイ！あなたの統計は堅実でバランスの取れた戦略を示しています。この調子で続けてください！",
        rec_limp_high: "🐠 **リンプを減らす**: リンプは受動的で、一般的に損失を生むプレイです。ミドルペアなどの手札でも、リンプの代わりにレイズして主導権を握ることを試してください。",
        rec_vpip_high: "🎰 **レンジを絞る (VPIP)**: あなたのVPIPが高すぎます。これは弱すぎるハンドをプレイしすぎていることを意味します。特にアーリーポジションでは、スターティングハンドの選択を絞り、規律を守りましょう。",
        rec_vpip_low: "🗿 **レンジを広げる (VPIP)**: あなたはプレイがタイトすぎて、多くの利益機会を逃している可能性があります。特にレイトポジション（CO、BTN）では、より広いレンジでオープンや3ベットを試してください。",
        rec_vpip_pfr_gap: "🤔 **プリフロップのアグレッシブさを高める**: VPIPとPFRの差が大きいのは、コールが多すぎるという受動的なプレイを示しています。優秀なプレイヤーは、コールよりもレイズかフォールドを選択する傾向があります。",
        rec_3bet_low: "💣 **3ベットの頻度を増やす**: あなたの3ベット頻度は低すぎます。3ベットを増やすことで、デッドマネーを獲得し、弱いプレイヤーを孤立させ、強いハンドでより多くのバリューを得ることができます。",
        rec_4bet_low: "🚀 **4ベットの脅威を確立する**: 4ベット率が低すぎると、アグレッシブな相手は遠慮なく3ベットしてきます。3ベットに直面した際は、トップハンドだけでなく、ブラフとしての4ベットも混ぜたバランスの取れたレンジで対応すべきです。",
        rec_fold_vs_3bet_high: "🛡️ **3ベットに対する防御を強化する**: 3ベットに対してフォールドしすぎているため、あなたのオープンは簡単に搾取されています。より広い、バランスの取れたレンジでコールするか、4ベットで反撃する必要があります。",
        rec_steal_low: "🏴‍☠️ **もっと積極的にスティールする**: ブラインドはテーブル上のフリーマネーです！COやBTNから積極的にブラインドをスティールすることは、安定した利益を得るための鍵です。35%以上を目指しましょう。",
        rec_fold_to_steal_high: "💰 **ブラインドの防御を強化する**: あなたはブラインドをあまりにも簡単に諦めすぎています。スティールに対しては、より広いレンジで3ベットやコールを行い、ブラインドを守るべきです。",
        rec_cbet_low: "📉 **C-Bet頻度を増やす**: プリフロップで主導権を握っていますが、フロップでプレッシャーをかけ続けていません。有利なボードテクスチャでは、もっと頻繁にC-Betを行うべきです。",
        rec_cbet_high: "💥 **C-Bet頻度を最適化する**: あなたはC-Betしすぎています。マルチウェイポットや不利なボード、手強い相手に対しては、チェックバックしてポットサイズをコントロールすることを学び、予測されにくいゲームにしましょう。",
        rec_fold_to_cbet_high: "✋ **C-Betに対するフォールドを減らす**: 相手のC-Betは常に強いハンドを表しているわけではありません。ドローやバックドアドロー、ペアなどで相手のベットを『フロート』（Float）したり、ブラフとしてレイズして反撃することを学びましょう。",
        rec_wtsd_low: "⏳ **ポットを早すぎる段階で諦めない**: あなたはショーダウン前にフォールドしすぎており、簡単にブラフされています。ポットオッズとハンドのエクイティを評価し、ショーダウンバリューのあるハンドで最後までコールすることを検討してください。",
        rec_wtsd_high_wtsd_won_low: "💸 **コーリングステーションにならない**: WTSDが高いのにW$SDが低いのは、弱すぎるハンドで最後までコールしすぎていることを示唆しています。難しいフォールドをすることで、大金を節約できます。",
        rec_afq_low: "🕊️ **ポストフロップのアグレッシブさを高める (AFq)**: あなたのポストフロップのアグレッシブさは低いです。受動的にチェックやコールをする代わりに、もっとベットやレイズの機会を探しましょう。",

        // --- About Page (Updated) ---
        about_github_link: "GitHubプロジェクトを見る",
        about_title: "このプロジェクトについて",
        about_p1: "PokerTrackerやHold'em Managerのような複雑な設定やサブスクリプションが必要なプロのトラッキングソフトウェアとは異なり、このツールは<strong>軽量、高速、無料、そして安全</strong>な代替品となることを目指しています。私たちは<strong>ウェブ体験</strong>に焦点を当てており、ソフトウェアをインストールする必要はありません。ブラウザを開くだけで、デスクトップでもモバイルデバイスでも、いつでもどこでも素早くセッションをレビューし、自分の強みと改善点を見つけることができます。",
        report_strengths_title: "強み",
        report_strength1: "<strong>完全無料＆オープンソース:</strong> 利用コストは一切かかりません。コードは透明性が高く、信頼できます。",
        report_strength2: "<strong>高いプライバシー保護:</strong> すべての計算はユーザーのデバイス上でローカルに実行されます。ハンドデータがサーバーに送信されることはなく、データ漏洩のリスクがありません。",
        report_strength3: "<strong>クロスプラットフォーム＆インストール不要:</strong> どのモダンブラウザでも動作するため、どのデバイスからでも利用できます。",
        report_strength4: "<strong>データの携帯性＆蓄積:</strong> 分析結果はJSONファイルとしてエクスポートでき、個人的なバックアップや、新しいセッションと結合して長期的なデータ追跡を行うことができます。",
        report_strength5: "<strong>直感的なデータ視覚化:</strong> 単純なテキストファイルを読むよりも、チャートやグラフで自分のパフォーマンス傾向を理解しやすくなっています。",
        report_weaknesses_title: "課題",
        report_weakness1: "<strong>リアルタイムHUD機能なし:</strong> プロのソフトウェアとは異なり、テーブル上でリアルタイムに対戦相手のスタッツを表示することはできません。",
        report_weakness2: "<strong>手動アップロードが必要:</strong> GGPokerクライアントから手動でハンド履歴をエクスポートし、アップロードする必要があります。",
        report_weakness3: "<strong>基本的な指標:</strong> コアとなるスタッツはカバーしていますが、プロのツールに比べると詳細さが劣ります（例：特定のハンドタイプごとの利益分析は提供していません）。",
        report_weakness4: "<strong>フロントエンドのパフォーマンスボトルネック:</strong> 数十万ハンドに達すると、クライアントサイドのJavaScript計算が遅くなったり、ブラウザが重くなる可能性があります。",
        report_weakness5: "<strong>対戦相手分析機能なし:</strong> このツールは完全に『ヒーロー』自身のデータに焦点を当てており、特定の対戦相手を分析するためのデータベースを構築しません。",
        report_future_title: "将来のロードマップ",
        report_future1: "<strong>クラウドバックエンドの統合:</strong> 計算負荷の高い解析と統計作業をバックエンドサービスに移行し、フロントエンドのパフォーマンスボトルネックを解決します。",
        report_future2: "<strong>ユーザーアカウント＆データ同期:</strong> ユーザーアカウントを導入し、分析結果をクラウドに自動保存することで、デバイス間のデータ同期を可能にします。",
        report_future3: "<strong>ハンドのビジュアルリプレイ:</strong> 選択したハンドをクリックして、グラフィカルなインターフェースで完全なプロセスをリプレイする機能を追加します。",
        report_future4: "<strong>高度なデータフィルター:</strong> ポジション、スターティングハンド、ポットサイズなど、複数の次元でデータをフィルタリングできるようにし、より深い分析を可能にします。",
        report_future5: "<strong>スターティングハンドマトリックスヒートマップ:</strong> 13x13のグリッドで、すべてのスターティングハンドのVPIP、PFR、利益などのデータを表示します。",
        report_future6: "<strong>特定のゲーム/ステークス分析:</strong> 特定のステークスレベルやゲームタイプ（例：Rush & Cash）のみを分析するフィルタ機能を追加します。",
        report_future7: "<strong>より豊富なチャートタイプ:</strong> 円グラフ（アクション分布）やレーダーチャート（プレイヤースタイルの全体像）などを追加します。",
        report_future8: "<strong>簡単な対戦相手タグ付け:</strong> 完全なHUDではありませんが、レビュー中に特定の対戦相手IDにタグ（例：フィッシュ、TAG）を追加できるようにします。",
        report_future9: "<strong>目標志向型学習モジュール:</strong> 特定された統計的な弱点に基づいて、関連するポーカースタディリソースや記事へのリンクを自動で推奨します。",
        report_future10: "<strong>共有可能なレポート:</strong> コーチや友人とデータを議論するために、共有可能な読み取り専用のレポートページリンクを生成します。",
    },
    ko: {
        // --- 통용 UI ---
        title: "GGPoker 핸드 분석기",
        subtitle: "데이터 기반 의사결정, 승리로의 통찰",
        upload_title: "핸드 내역 업로드",
        analyze_data: "분석 시작",
        download_data: "원본 데이터 다운로드",
        clear_all: "모두 지우기",
        loading: "데이터를 분석 중입니다...",
        welcome_title: "GGPoker 핸드 분석기에 오신 것을 환영합니다",
        welcome_p1: "GGPoker .txt 핸드 내역 파일을 업로드하여 플레이 스타일, 수익성 및 잠재적 약점에 대한 깊은 통찰력을 얻으십시오.",
        upload_click: "클릭하거나 파일을 여기로 드래그하여 업로드",
        upload_drag: ".txt, .json 형식 지원",
        upload_supported: "모든 데이터는 개인 정보 보호를 위해 귀하의 브라우저에서 로컬로 처리됩니다.",
        analysis_options: "분석 옵션",
        uploaded_files: "업로드된 파일",
        no_files_uploaded: "아직 업로드된 파일이 없습니다",
        game_type_all: "모든 게임 유형",
        game_type_holdem: "홀덤",
        game_type_omaha: "오마하",
        error_no_data: "유효한 핸드 내역 데이터를 찾을 수 없습니다. 파일 내용을 확인하십시오.",
        error_no_data_in_filter: "이 게임 유형에는 데이터가 없습니다. '모든 게임 유형'을 선택해 보십시오.",
        error_generic: "분석 중 오류가 발생했습니다. 파일을 확인하거나 나중에 다시 시도하십시오.",
        
        // --- 탭 ---
        tab_overview: "대시보드", tab_preflop: "프리플랍", tab_postflop: "포스트플랍",
        tab_position: "위치", tab_time: "시간", tab_recommendations: "권장사항", tab_about: "정보",

        // --- 섹션 제목 ---
        win_rate_stats: "수익성", preflop_style: "프리플랍 스타일", postflop_play: "포스트플랍 플레이",
        session_info: "세션 정보", profit_chart_title: "총 이익 차트 ($)",
        preflop_open: "프리플랍 오픈", preflop_vs_raise: "레이즈에 대해", steal_dynamics: "스티일 다이내믹스",
        postflop_as_aggressor: "프리플랍 어그레서로서", postflop_as_caller: "프리플랍 콜러로서",
        showdown_stats: "쇼다운 통계", aggression_stats: "스트리트별 공격성",
        positional_profit: "위치별 수익성 (BB/100)",
        positional_style: "위치별 플레이 스타일", positional_aggression: "위치별 3-Bet 빈도",
        positional_cbet: "위치별 C-Bet 빈도", positional_wtsd: "위치별 쇼다운 비율", 
        winrate_by_weekday: "요일별 승률 분석 (BB/100)", winrate_by_hour: "시간별 승률 분석 (BB/100)",
        player_style_radar: "플레이어 스타일 레이더 차트",

        // --- 데이터 지표 & 툴팁 ---
        total_hands: "총 핸드 수", tooltip_total_hands: "분석된 총 핸드 수입니다.",
        total_profit: "총 이익", tooltip_total_profit: "귀하의 총 이익 또는 손실 금액입니다.",
        bb_per_100: "BB/100", tooltip_bb_per_100: "100 핸드당 평균 이익(빅 블라인드 기준). 이는 귀하의 실제 승률을 측정하는 핵심 지표입니다.",
        profit_bb: "총 이익 (BB)", tooltip_profit_bb: "빅 블라인드 기준 총 이익 또는 손실입니다.",
        total_rake: "총 레이크", tooltip_total_rake: "이 세션에서 기여한 총 레이크 금액(기본 레이크 및 잭팟 포함).",
        total_profit_with_rake: "총 이익 (레이크 포함)", tooltip_total_profit_with_rake: "귀하의 총 이익 또는 손실 금액으로, 획득한 팟과 기여한 레이크를 포함합니다.",
        bb_with_rake_per_100: "BB/100 (레이크 포함)", tooltip_bb_with_rake_per_100: "100 핸드당 평균 이익(빅 블라인드 기준)으로, 레이크가 포함됩니다. 이는 귀하의 실제 승률을 측정하는 핵심 지표입니다.",
        profit_with_rake_bb: "총 이익 (레이크 포함, BB)", tooltip_profit_with_rake_bb: "빅 블라인드 기준 총 이익 또는 손실로, 레이크가 포함됩니다.",
        total_jackpot: "총 잭팟", tooltip_total_jackpot: "핸드에서 누적된 총 잭팟 금액입니다.",
        
        vpip: "VPIP", tooltip_vpip: "Voluntarily Put in Pot (자발적으로 팟에 참여). 플레이의 느슨함/타이트함을 측정하는 핵심 지표입니다. 이상적인 범위는 약 20-28%입니다.",
        pfr: "PFR", tooltip_pfr: "Pre-Flop Raise (프리플랍 레이즈). 프리플랍 공격성을 측정하는 지표입니다. 이상적인 범위는 약 15-23%입니다.",
        limp: "림프 %", tooltip_limp: "아무도 레이즈하지 않은 상황에서, 첫 번째로 콜하는 빈도. 높은 수준의 플레이어는 이 수치가 0에 가깝습니다.",

        "3bet": "3Bet PF", tooltip_3bet: "프리플랍 3-Bet. 오픈 레이즈에 대해 리레이즈하는 빈도. 이상적인 범위는 약 7-12%입니다.",
        "4bet": "4Bet PF", tooltip_4bet: "프리플랍 4-Bet. 3-Bet에 대해 리레이즈하는 빈도.",
        fold_vs_3bet: "3-Bet에 대한 폴드", tooltip_fold_vs_3bet: "오픈 레이즈 후, 3-Bet에 대해 폴드하는 빈도. 너무 높으면 (>65%) 오픈 레인지가 쉽게 착취당합니다.",
        fold_vs_4bet: "4-Bet에 대한 폴드", tooltip_fold_vs_4bet: "3-Bet 후, 상대방의 4-Bet에 대해 폴드하는 빈도.",
        cold_call: "콜드 콜", tooltip_cold_call: "아직 팟에 돈을 투자하지 않은 상태에서 레이즈를 콜하는 빈도입니다.",
        squeeze: "스퀴즈", tooltip_squeeze: "레이즈와 한 명 이상의 콜러가 있을 때 리레이즈하는 빈도입니다.",

        steal_attempt: "스티일 시도", tooltip_steal_attempt: "CO 또는 BTN에서 앞선 플레이어가 모두 폴드했을 때 오픈 레이즈하는 빈도. 35% 이상이어야 합니다.",
        fold_to_steal: "스티일에 대한 폴드", tooltip_fold_to_steal: "블라인드에서 CO 또는 BTN의 오픈 레이즈에 대해 폴드하는 빈도. 75% 미만이어야 합니다.",
        
        cbet_flop: "C-Bet 플랍", tooltip_cbet_flop: "프리플랍 어그레서로서, 플랍에서 계속 베팅하는 빈도. 이상적인 범위는 50-75%입니다.",
        cbet_turn: "C-Bet 턴", tooltip_cbet_turn: "플랍에서 C-Bet 후, 턴에서 계속 베팅하는 빈도.",
        cbet_river: "C-Bet 리버", tooltip_cbet_river: "턴에서 C-Bet 후, 리버에서 계속 베팅하는 빈도.",

        fold_to_cbet_flop: "C-Bet에 대한 폴드", tooltip_fold_to_cbet_flop: "상대방의 C-Bet에 대해 플랍에서 폴드하는 빈도. 너무 높으면 (>60%) 포스트플랍에서 너무 많이 폴드하는 것입니다.",
        raise_cbet_flop: "C-Bet에 대한 레이즈", tooltip_raise_cbet_flop: "상대방의 C-Bet에 대해 플랍에서 레이즈하는 빈도입니다.",
        check_raise_flop: "체크-레이즈", tooltip_check_raise_flop: "플랍에서 먼저 체크한 후 상대방의 베팅에 대해 레이즈하는 빈도입니다.",
        donk_bet_flop: "돈크 벳", tooltip_donk_bet_flop: "프리플랍 어그레서가 행동하기 전에 먼저 베팅하는 빈도. 이 수치는 매우 낮아야 합니다.",
        bet_vs_missed_cbet: "C-Bet 놓침에 대한 벳", tooltip_bet_vs_missed_cbet: "프리플랍 어그레서가 플랍에서 체크백할 때 베팅하는 빈도입니다.",
        probe_bet_turn: "프로브 벳 턴", tooltip_probe_bet_turn: "플랍에서 모두가 체크한 후, 턴에서 첫 번째로 베팅하는 빈도입니다.",
        
        wtsd: "WTSD", tooltip_wtsd: "Went To Showdown (쇼다운까지 갔다). 플랍을 본 후 쇼다운까지 가는 빈도. 이상적인 범위는 25-32%입니다.",
        wtsd_won: "W$SD", tooltip_wtsd_won: "Won at Showdown (쇼다운에서 이겼다). 쇼다운에서 팟을 이기는 빈도. 50% 이상이어야 합니다.",
        wwsf: "WWSF", tooltip_wwsf: "Won When Saw Flop (플랍을 보고 이겼다). 플랍을 본 후 최종적으로 팟을 이기는 빈도.",
        wtsd_after_cbet: "C-Bet 후 WTSD", tooltip_wtsd_after_cbet: "플랍에서 C-Bet을 한 후 최종적으로 쇼다운까지 가는 빈도입니다.",
        wwsf_as_pfr: "PFR로서의 WWSF", tooltip_wwsf_as_pfr: "프리플랍 어그레서였을 때 플랍을 본 후 팟을 이기는 빈도입니다.",
        wwsf_as_caller: "콜러로서의 WWSF", tooltip_wwsf_as_caller: "프리플랍 콜러였을 때 플랍을 본 후 팟을 이기는 빈도입니다.",
        
        afq_flop: "AFq 플랍", tooltip_afq_flop: "플랍 공격성 빈도: (베팅 + 레이즈) / (베팅 + 레이즈 + 콜 + 체크).",
        afq_turn: "AFq 턴", tooltip_afq_turn: "턴 공격성 빈도.",
        afq_river: "AFq 리버", tooltip_afq_river: "리버 공격성 빈도.",
        preflop_aggression: "프리플랍 공격성", tooltip_preflop_aggression: "프리플랍 공격성 지표 (PFR/VPIP). 이 수치가 높을수록 프리플랍 스타일이 더 공격적이며 수동적인 콜이 적다는 것을 의미합니다. 이상적인 값은 약 70-90%입니다.",
        afq_all: "종합 포스트플랍 공격성", tooltip_afq_all: "종합 포스트플랍 공격성 빈도. 플랍, 턴, 리버 세 스트리트의 공격성 빈도(AFq)의 평균값으로, 포스트플랍에서의 전반적인 공격성을 종합적으로 측정합니다.",
        
        total_duration: "총 시간", tooltip_total_duration: "모든 개별 게임 세션의 총 시간. 인접한 핸드 사이에 45분 이상 간격이 있으면 새로운 세션으로 간주됩니다.",
        hands_per_hour: "핸드 수/시간", tooltip_hands_per_hour: "시간당 플레이한 평균 핸드 수입니다.",
        profit_per_hour: "시간당 이익 ($)", tooltip_profit_per_hour: "미국 달러 기준 시간당 평균 이익입니다.",
        profit_with_rake_per_hour: "시간당 이익 (레이크 포함, $)", tooltip_profit_with_rake_per_hour: "미국 달러 기준 시간당 평균 이익으로, 레이크가 포함됩니다.",

        tooltip_delete_file: "이 파일 삭제",
        
        // --- 권장 사항 ---
        rec_title: "📈 맞춤형 권장 사항",
        rec_good: "훌륭한 플레이입니다! 당신의 통계는 견고하고 균형 잡힌 전략을 보여줍니다. 계속 유지하십시오!",
        rec_limp_high: "🐠 **림프 줄이기**: 림프는 수동적이며 일반적으로 손실이 발생하는 플레이입니다. 중간 핸드라도 림프 대신 레이즈하여 주도권을 잡으십시오.",
        rec_vpip_high: "🎰 **레인지 좁히기 (VPIP)**: VPIP가 너무 높습니다. 이는 너무 많은 약한 핸드를 플레이하고 있다는 의미입니다. 특히 앞선 포지션에서는 시작 핸드 선택을 엄격하게 하십시오.",
        rec_vpip_low: "🗿 **레인지 넓히기 (VPIP)**: 너무 타이트하게 플레이하고 있어서 수익성 있는 기회를 놓치고 있을 수 있습니다. 특히 늦은 포지션(CO, BTN)에서는 더 넓은 레인지로 오픈하고 3-Bet을 시도하십시오.",
        rec_vpip_pfr_gap: "🤔 **프리플랍 공격성 높이기**: VPIP와 PFR의 차이가 크다는 것은 수동적인 플레이(콜이 너무 많음)를 의미합니다. 수익성 있는 플레이어는 콜보다는 레이즈 또는 폴드를 선호합니다.",
        rec_3bet_low: "💣 **3-Bet 빈도 늘리기**: 3-Bet 빈도가 너무 낮습니다. 3-Bet을 더 자주하면 데드 머니를 더 많이 얻고, 약한 플레이어를 고립시키며, 강한 핸드로 더 많은 가치를 얻을 수 있습니다.",
        rec_4bet_low: "🚀 **4-Bet 위협 구축**: 4-Bet 비율이 너무 낮으면 공격적인 상대방이 거리낌 없이 3-Bet할 수 있습니다. 3-Bet에 직면했을 때, 최상위 강한 핸드 외에도 일부 블러프 4-Bet을 섞어서 사용해야 합니다.",
        rec_fold_vs_3bet_high: "🛡️ **3-Bet 방어 강화**: 3-Bet에 너무 많이 폴드하면 상대방이 오픈 레이즈를 쉽게 착취할 수 있습니다. 더 넓고 균형 잡힌 레인지로 콜하거나 4-Bet으로 반격해야 합니다.",
        rec_steal_low: "🏴‍☠️ **블라인드 더 적극적으로 스틸하기**: 블라인드는 테이블 위의 주인이 없는 보물입니다! CO와 BTN 포지션에서 적극적으로 블라인드를 스틸하는 것은 안정적인 수익의 핵심입니다. 35% 이상을 목표로 하십시오.",
        rec_fold_to_steal_high: "💰 **블라인드 방어 강화**: 너무 쉽게 블라인드를 포기하고 있습니다. 스틸에 대해 더 넓은 레인지로 3-Bet하거나 콜하여 블라인드를 방어해야 합니다.",
        rec_cbet_low: "📉 **컨티뉴에이션 벳 (C-Bet) 빈도 늘리기**: 프리플랍에서 주도권을 잡았지만 플랍에서 압박을 계속하지 않고 있습니다. 유리한 보드 구조에서는 더 자주 C-Bet을 해야 합니다.",
        rec_cbet_high: "💥 **C-Bet 빈도 최적화**: 너무 자주 C-Bet을 하고 있습니다. 멀티웨이 팟, 불리한 보드 또는 어려운 상대방에 대해 체크로 팟을 통제하는 방법을 배우면 예측하기 어려운 플레이를 할 수 있습니다.",
        rec_fold_to_cbet_high: "✋ **C-Bet에 대한 폴드 줄이기**: 상대방의 C-Bet이 항상 강한 핸드를 의미하는 것은 아닙니다. 드로우, 백도어 드로우 또는 페어로 상대를 '플로팅'(Float)하거나 레이즈로 반격하는 방법을 배우십시오.",
        rec_wtsd_low: "⏳ **너무 일찍 팟을 포기하지 않기**: 쇼다운 전에 너무 자주 폴드하고 있어서 상대방에게 쉽게 블러프를 당할 수 있습니다. 팟 오즈와 핸드의 에퀴티를 평가하여 쇼다운 가치가 있는 핸드로 끝까지 콜하는 것을 고려하십시오.",
        rec_wtsd_high_wtsd_won_low: "💸 **콜링 스테이션이 되지 않기**: WTSD가 높지만 W$SD가 낮은 것은 너무 많은 약한 핸드로 끝까지 콜하고 있다는 것을 의미합니다. 어려운 폴드를 하는 법을 배우면 큰 금액을 아낄 수 있습니다.",
        rec_afq_low: "🕊️ **포스트플랍 공격성 높이기 (AFq)**: 포스트플랍 공격성 빈도가 낮습니다. 수동적으로 체크하거나 콜하는 대신, 베팅하고 레이즈할 기회를 더 많이 찾으십시오.",

        // --- About Page (Updated) ---
        about_github_link: "GitHub 프로젝트 보기",
        about_title: "이 프로젝트에 대해",
        about_p1: "복잡한 설정과 구독료가 필요한 PokerTracker, Hold'em Manager와 같은 전문 트래킹 소프트웨어와 달리, 이 도구는 <strong>가볍고 빠르며 무료이고 안전한</strong> 대안을 제공하는 것을 목표로 합니다. 저희는 <strong>웹 경험</strong>에 중점을 두어, 소프트웨어를 설치할 필요 없이 브라우저만 열면 데스크톱이든 모바일이든 언제 어디서나 빠르게 세션을 검토하고 자신의 강점과 개선점을 찾을 수 있습니다.",
        report_strengths_title: "강점",
        report_strength1: "<strong>완전 무료 및 오픈 소스:</strong> 사용 비용이 전혀 들지 않습니다. 코드는 투명하여 신뢰성이 높습니다.",
        report_strength2: "<strong>높은 개인 정보 보호:</strong> 모든 계산은 사용자 장치에서 로컬로 완료됩니다. 핸드 데이터는 서버를 거치지 않으므로 데이터 유출 위험이 없습니다.",
        report_strength3: "<strong>크로스 플랫폼, 설치 불필요:</strong> 모든 최신 브라우저에서 작동하므로 어떤 장치에서도 편리하게 사용할 수 있습니다.",
        report_strength4: "<strong>데이터 이식성 및 누적:</strong> 분석 결과는 JSON 파일로 내보내어 개인 백업으로 사용하거나, 다음에 새로운 세션과 병합하여 장기적인 데이터 추적을 할 수 있습니다.",
        report_strength5: "<strong>직관적인 데이터 시각화:</strong> 단순한 텍스트 파일을 읽는 것보다 차트와 그래프를 통해 자신의 성능 추세를 더 쉽게 이해할 수 있습니다.",
        report_weaknesses_title: "단점",
        report_weakness1: "<strong>실시간 HUD 기능 부재:</strong> 전문 소프트웨어와 달리 테이블에서 상대방 통계를 실시간으로 표시할 수 없습니다.",
        report_weakness2: "<strong>수동 업로드 필요:</strong> GGPoker 클라이언트에서 수동으로 내역을 내보내고 업로드해야 하므로, 자동 임포트 소프트웨어만큼 편리하지 않습니다.",
        report_weakness3: "<strong>기본적인 데이터 차원:</strong> 현재 제공되는 데이터 지표는 핵심적이지만, 전문 소프트웨어에 비해 세부적이지 않습니다 (예: 특정 핸드 조합의 수익 분석 부재).",
        report_weakness4: "<strong>프론트엔드 계산 성능 병목:</strong> 수십만 핸드에 도달하면 순수 프론트엔드 JavaScript 계산이 성능 병목 현상을 일으킬 수 있습니다.",
        report_weakness5: "<strong>상대방 분석 기능 부재:</strong> 이 도구는 사용자(히어로) 자신의 데이터에만 초점을 맞추고 있어, 상대방 데이터베이스를 구축하여 맞춤형 분석을 할 수 없습니다.",
        report_future_title: "미래 로드맵",
        report_future1: "<strong>클라우드 백엔드 통합:</strong> 계산 집약적인 파싱 및 통계 작업을 백엔드로 이동하여 프론트엔드 성능 병목 현상을 해결합니다.",
        report_future2: "<strong>사용자 계정 시스템:</strong> 계정 시스템을 도입하여 사용자가 분석 결과를 클라우드에 자동으로 저장하고 장치 간 데이터 동기화를 할 수 있도록 합니다.",
        report_future3: "<strong>핸드 시각화 리플레이:</strong> 단일 핸드 내역을 클릭하여 그래픽 인터페이스로 핸드의 전체 과정을 리플레이하는 기능을 추가합니다.",
        report_future4: "<strong>고급 데이터 필터:</strong> 사용자가 위치, 시작 핸드, 판 결과 등 여러 차원으로 데이터를 필터링할 수 있도록 하여 더 깊은 분석을 가능하게 합니다.",
        report_future5: "<strong>시작 핸드 매트릭스 히트맵:</strong> 13x13 매트릭스 차트로 모든 시작 핸드의 VPIP, PFR, 이익 등의 데이터를 표시합니다.",
        report_future6: "<strong>특정 게임/블라인드 분석:</strong> 특정 블라인드 레벨 또는 게임 유형(예: Rush & Cash)만 분석할 수 있는 필터 기능을 추가합니다.",
        report_future7: "<strong>더 풍부한 차트 유형:</strong> 파이 차트(액션 분포), 레이더 차트(플레이어 스타일 평가) 등을 추가합니다.",
        report_future8: "<strong>간단한 상대방 데이터 태깅:</strong> 완벽한 HUD는 아니지만, 분석 중에 특정 상대방 ID에 태그(예: 피쉬, TAG)를 추가할 수 있도록 허용합니다.",
        report_future9: "<strong>목표 지향적 학습 모듈:</strong> 데이터 약점에 따라 관련 포커 학습 자료 또는 기사 링크를 자동으로 추천합니다.",
        report_future10: "<strong>커뮤니티 공유 보고서:</strong> 코치나 친구와 데이터를 논의할 수 있도록 공유 가능한 읽기 전용 보고서 페이지 링크를 생성합니다.",
    },
    es: {
        // --- General UI ---
        title: "Analizador de Manos de GGPoker",
        subtitle: "Decisiones basadas en datos, Perspectivas hacia la victoria",
        upload_title: "Subir Historial de Manos",
        analyze_data: "Comenzar Análisis",
        download_data: "Descargar Datos Brutos",
        clear_all: "Borrar Todo",
        loading: "Analizando sus datos...",
        welcome_title: "Bienvenido al Analizador de Manos de GGPoker",
        welcome_p1: "Suba sus archivos de historial de manos .txt de GGPoker para obtener una visión profunda de su estilo de juego, rentabilidad y posibles fugas.",
        upload_click: "Haga clic o arrastre el archivo aquí para subir",
        upload_drag: "Soporta formatos .txt, .json",
        upload_supported: "Todos los datos se procesan localmente en su navegador para su privacidad.",
        analysis_options: "Opciones de Análisis",
        uploaded_files: "Archivos Subidos",
        no_files_uploaded: "No se ha subido ningún archivo aún",
        game_type_all: "Todos los Tipos de Juego",
        game_type_holdem: "Hold'em",
        game_type_omaha: "Omaha",
        error_no_data: "No se encontraron datos válidos de historial de manos. Por favor, verifique el contenido del archivo.",
        error_no_data_in_filter: "No hay datos disponibles para este tipo de juego. Intente seleccionar 'Todos los Tipos de Juego'.",
        error_generic: "Ocurrió un error durante el análisis. Por favor, revise sus archivos o inténtelo de nuevo más tarde.",
        
        // --- Pestañas ---
        tab_overview: "Panel de Control", tab_preflop: "Preflop", tab_postflop: "Postflop",
        tab_position: "Posición", tab_time: "Tiempo", tab_recommendations: "Recomendaciones", tab_about: "Acerca de",

        // --- Títulos de Bloque ---
        win_rate_stats: "Rentabilidad", preflop_style: "Estilo Preflop", postflop_play: "Juego Postflop",
        session_info: "Información de Sesión", profit_chart_title: "Gráfico de Ganancias Totales ($)",
        preflop_open: "Apertura Preflop", preflop_vs_raise: "Contra Raise", steal_dynamics: "Dinámica de Robo",
        postflop_as_aggressor: "Como Agresor Preflop", postflop_as_caller: "Como Caller Preflop",
        showdown_stats: "Estadísticas de Showdown", aggression_stats: "Agresividad por Calle",
        positional_profit: "Rentabilidad Posicional (BB/100)",
        positional_style: "Estilo de Juego Posicional", positional_aggression: "Frecuencia de 3-Bet Posicional",
        positional_cbet: "Frecuencia de C-Bet Posicional", positional_wtsd: "% de WTSD Posicional", 
        winrate_by_weekday: "Tasa de Ganancia por Día de la Semana (BB/100)", winrate_by_hour: "Tasa de Ganancia por Hora (BB/100)",
        player_style_radar: "Gráfico de Radar del Estilo del Jugador",

        // --- Métricas y Tooltips ---
        total_hands: "Total de Manos", tooltip_total_hands: "El número total de manos analizadas.",
        total_profit: "Ganancia Total", tooltip_total_profit: "Su cantidad total de ganancias o pérdidas.",
        bb_per_100: "BB/100", tooltip_bb_per_100: "Ganancia promedio por cada 100 manos en ciegas grandes. Es una métrica central para su verdadera tasa de ganancia.",
        profit_bb: "Ganancia Total (BB)", tooltip_profit_bb: "Ganancia o pérdida total en términos de ciegas grandes.",
        total_rake: "Rake Total", tooltip_total_rake: "La cantidad total de rake que usted contribuyó (incluyendo rake base y jackpot).",
        total_profit_with_rake: "Ganancia Total (c/ Rake)", tooltip_total_profit_with_rake: "Su ganancia o pérdida total, incluyendo los botes ganados y el rake contribuido.",
        bb_with_rake_per_100: "BB/100 (c/ Rake)", tooltip_bb_with_rake_per_100: "Ganancia promedio por cada 100 manos en ciegas grandes, con el rake considerado. Es una métrica central para su verdadera tasa de ganancia.",
        profit_with_rake_bb: "Ganancia Total (c/ Rake, BB)", tooltip_profit_with_rake_bb: "Su ganancia o pérdida total en ciegas grandes, incluyendo el rake.",
        total_jackpot: "Jackpot Total", tooltip_total_jackpot: "La cantidad total de jackpot que ha acumulado en sus manos.",
        
        vpip: "VPIP", tooltip_vpip: "Voluntariamente Puesto en el Bote. Mide qué tan suelto/apretado juega. El rango ideal es alrededor del 20-28%.",
        pfr: "PFR", tooltip_pfr: "Pre-Flop Raise. Mide su agresividad preflop. El rango ideal es alrededor del 15-23%.",
        limp: "% de Limp", tooltip_limp: "Frecuencia con la que entra al bote haciendo call en lugar de raise, cuando nadie ha subido aún. Los jugadores de alto nivel tienen esta estadística cerca de 0.",

        "3bet": "3Bet PF", tooltip_3bet: "Porcentaje de 3-Bet preflop. Frecuencia con la que resube un raise de apertura. El rango ideal es alrededor del 7-12%.",
        "4bet": "4Bet PF", tooltip_4bet: "Porcentaje de 4-Bet preflop. Frecuencia con la que resube un 3-bet.",
        fold_vs_3bet: "Fold a 3-Bet", tooltip_fold_vs_3bet: "Frecuencia de foldear a un 3-bet después de haber abierto con un raise. Demasiado alto (>65%) es explotable.",
        fold_vs_4bet: "Fold a 4-Bet", tooltip_fold_vs_4bet: "Frecuencia de foldear a un 4-bet después de haber hecho un 3-bet.",
        cold_call: "Cold Call", tooltip_cold_call: "Frecuencia de hacer call a un raise cuando aún no ha invertido dinero en el bote.",
        squeeze: "Squeeze", tooltip_squeeze: "Frecuencia de resubir cuando ha habido un raise y uno o más callers antes que usted.",

        steal_attempt: "Intento de Robo", tooltip_steal_attempt: "Frecuencia con la que abre con un raise desde CO o BTN. Debería ser superior al 35%.",
        fold_to_steal: "Fold a Robo", tooltip_fold_to_steal: "Frecuencia con la que foldea desde las ciegas a un intento de robo. Debería ser inferior al 75%.",
        
        cbet_flop: "C-Bet Flop", tooltip_cbet_flop: "Apuesta de continuación en el flop como agresor preflop. El rango ideal es 50-75%.",
        cbet_turn: "C-Bet Turn", tooltip_cbet_turn: "Apuesta de continuación en el turn después de haber hecho c-bet en el flop.",
        cbet_river: "C-Bet River", tooltip_cbet_river: "Apuesta de continuación en el river después de haber hecho c-bet en el turn.",

        fold_to_cbet_flop: "Fold a C-Bet", tooltip_fold_to_cbet_flop: "Frecuencia de foldear a una C-Bet en el flop. Demasiado alto (>60%) significa que está foldeando demasiado postflop.",
        raise_cbet_flop: "Raise a C-Bet", tooltip_raise_cbet_flop: "Frecuencia de resubir una apuesta de continuación de un oponente en el flop.",
        check_raise_flop: "Check-Raise", tooltip_check_raise_flop: "Frecuencia de hacer check y luego subir una apuesta de un oponente en el flop.",
        donk_bet_flop: "Donk Bet", tooltip_donk_bet_flop: "Frecuencia de apostar fuera de posición antes de que el agresor preflop haya actuado. Debería ser muy bajo.",
        bet_vs_missed_cbet: "Bet contra C-Bet fallida", tooltip_bet_vs_missed_cbet: "Frecuencia de apostar cuando el agresor preflop ha hecho check back en el flop.",
        probe_bet_turn: "Probe Bet Turn", tooltip_probe_bet_turn: "Frecuencia de apostar en el turn cuando el flop fue checkeado por todos.",
        
        wtsd: "WTSD", tooltip_wtsd: "Went To Showdown (Llegó al Showdown). Frecuencia de llegar al showdown después de ver el flop. El rango ideal es 25-32%.",
        wtsd_won: "W$SD", tooltip_wtsd_won: "Won at Showdown (Ganó en el Showdown). Frecuencia de ganar el bote en el showdown. Debería ser superior al 50%.",
        wwsf: "WWSF", tooltip_wwsf: "Won When Saw Flop (Ganó cuando vio el Flop). Frecuencia de ganar el bote en cualquier momento después de ver el flop.",
        wtsd_after_cbet: "WTSD después de C-Bet", tooltip_wtsd_after_cbet: "Frecuencia de llegar al showdown después de haber hecho una apuesta de continuación en el flop.",
        wwsf_as_pfr: "WWSF como PFR", tooltip_wwsf_as_pfr: "Frecuencia de ganar el bote cuando fue el agresor preflop después de ver el flop.",
        wwsf_as_caller: "WWSF como Caller", tooltip_wwsf_as_caller: "Frecuencia de ganar el bote cuando fue un caller preflop después de ver el flop.",
        
        afq_flop: "AFq Flop", tooltip_afq_flop: "Frecuencia de agresividad en el flop: (Apuestas + Raises) / (Apuestas + Raises + Calls + Checks).",
        afq_turn: "AFq Turn", tooltip_afq_turn: "Frecuencia de agresividad en el turn.",
        afq_river: "AFq River", tooltip_afq_river: "Frecuencia de agresividad en el river.",
        preflop_aggression: "Agresividad Preflop", tooltip_preflop_aggression: "Factor de Agresividad Preflop (PFR/VPIP). Un valor más alto indica un estilo preflop más agresivo con menos calls pasivos. Un valor ideal es de alrededor del 70-90%.",
        afq_all: "Agresividad Postflop General", tooltip_afq_all: "Agresividad Postflop General. El promedio de la Frecuencia de Agresión (AFq) en el flop, turn y river, midiendo su agresividad postflop general.",
        
        total_duration: "Duración Total", tooltip_total_duration: "Duración total de todas las sesiones de juego. Se considera una nueva sesión después de un descanso de 45 minutos.",
        hands_per_hour: "Manos/Hora", tooltip_hands_per_hour: "Número promedio de manos jugadas por hora.",
        profit_per_hour: "Ganancia/Hora ($)", tooltip_profit_per_hour: "Ganancia promedio por hora en USD.",
        profit_with_rake_per_hour: "Ganancia/Hora (c/ Rake, $)", tooltip_profit_with_rake_per_hour: "Ganancia promedio por hora en USD, con el rake considerado.",

        tooltip_delete_file: "Eliminar este archivo",
        
        // --- Recomendaciones ---
        rec_title: "📈 Sus Recomendaciones Personalizadas",
        rec_good: "¡Excelente juego! Sus estadísticas muestran una estrategia sólida y equilibrada. ¡Siga así!",
        rec_limp_high: "🐠 **Reducir el Limping**: Limpear es una jugada pasiva y generalmente perdedora. Intente reemplazar los limps con raises para tomar el control del bote.",
        rec_vpip_high: "🎰 **Ajustar su Rango (VPIP)**: Su VPIP es demasiado alto, lo que significa que está jugando demasiadas manos débiles. Ajuste su selección de manos iniciales, especialmente desde posiciones tempranas.",
        rec_vpip_low: "🗿 **Ampliar su Rango (VPIP)**: Está jugando demasiado apretado y podría estar perdiendo oportunidades rentables. Intente abrir su rango, especialmente desde posiciones tardías (CO, BTN).",
        rec_vpip_pfr_gap: "🤔 **Aumentar la Agresividad Preflop**: Una gran brecha entre VPIP y PFR indica un juego pasivo (demasiados calls). Los jugadores rentables prefieren subir o foldear preflop.",
        rec_3bet_low: "💣 **Aumentar la Frecuencia de 3-Bet**: Su frecuencia de 3-bet es baja. Hacer 3-bet más a menudo no solo gana dinero muerto, sino que también aísla a los jugadores más débiles y obtiene más valor para sus manos fuertes.",
        rec_4bet_low: "🚀 **Establecer una Amenaza de 4-Bet**: Una baja tasa de 4-bet permite a los oponentes agresivos hacerle 3-bet sin cesar. Debe hacer 4-bet con un rango equilibrado de valor y bluffs.",
        rec_fold_vs_3bet_high: "🛡️ **Defenderse más contra los 3-Bets**: Está foldeando demasiado a los 3-bets, lo que hace que sus aperturas sean fácilmente explotables. Necesita defenderse haciendo call o 4-bet con un rango más amplio y equilibrado.",
        rec_steal_low: "🏴‍☠️ **Robar más Ciegas**: ¡Las ciegas son dinero gratis en la mesa! Robarlas agresivamente desde CO y BTN es crucial para su tasa de ganancia. Apunte a más del 35%.",
        rec_fold_to_steal_high: "💰 **Defender más sus Ciegas**: Está cediendo sus ciegas con demasiada facilidad. Debe defender sus ciegas contra robos más a menudo con 3-bets y calls.",
        rec_cbet_low: "📉 **Aumentar la Frecuencia de C-Bet**: Toma la iniciativa preflop pero no sigue la presión en el flop. Debe hacer apuestas de continuación más frecuentemente en texturas de mesa favorables.",
        rec_cbet_high: "💥 **Optimizar la Frecuencia de C-Bet**: Está haciendo c-bet con demasiada frecuencia. Aprenda a hacer check-back en mesas húmedas, en botes multiway o contra oponentes difíciles para hacer su juego menos predecible.",
        rec_fold_to_cbet_high: "✋ **Foldear menos a las C-Bets**: Las c-bets de los oponentes no siempre son manos fuertes. Aprenda a 'flotar' sus apuestas con proyectos o parejas, o incluso a resubir como un bluff para contraatacar.",
        rec_wtsd_low: "⏳ **No rendirse en los botes demasiado pronto**: Está foldeando antes del showdown con demasiada frecuencia y puede ser fácilmente bluffed. Considere las pot odds y la equidad de su mano para hacer mejores calls.",
        rec_wtsd_high_wtsd_won_low: "💸 **Evitar ser un 'Calling Station'**: Su WTSD es alto, pero su W$SD es bajo. Esto indica que está haciendo call hasta el final con demasiadas manos débiles. Aprenda a hacer folds difíciles para ahorrar dinero.",
        rec_afq_low: "🕊️ **Aumentar la Agresividad Postflop (AFq)**: Su agresividad postflop es baja. Busque más oportunidades para apostar y subir en lugar de hacer check y call pasivamente.",

        // --- Acerca de la Página (Actualizada) ---
        about_github_link: "Ver Proyecto en GitHub",
        about_title: "Acerca de este Proyecto",
        about_p1: "A diferencia de los programas de seguimiento profesionales como PokerTracker o Hold'em Manager, que requieren configuraciones complejas y suscripciones, esta herramienta busca ser una alternativa <strong>ligera, rápida, gratuita y segura</strong>. Nos enfocamos en la <strong>experiencia web</strong>, por lo que no necesita instalar nada. Simplemente abra su navegador, en su escritorio o dispositivo móvil, para revisar rápidamente sus sesiones en cualquier momento y lugar, y encontrar su ventaja.",
        report_strengths_title: "Fortalezas",
        report_strength1: "<strong>Completamente Gratuito y de Código Abierto:</strong> No hay costos involucrados. El código es transparente y confiable.",
        report_strength2: "<strong>Alta Protección de la Privacidad:</strong> Todos los cálculos se realizan localmente en su dispositivo. Los datos de las manos nunca tocan un servidor, eliminando el riesgo de fugas de datos.",
        report_strength3: "<strong>Multiplataforma y Sin Instalación:</strong> Funciona en cualquier navegador moderno, lo que lo hace accesible en cualquier dispositivo.",
        report_strength4: "<strong>Portabilidad y Acumulación de Datos:</strong> Los resultados del análisis se pueden exportar como un archivo JSON para su respaldo personal y se pueden volver a importar para fusionarlos con nuevas sesiones para un seguimiento a largo plazo.",
        report_strength5: "<strong>Visualización Intuitiva de Datos:</strong> Los gráficos y diagramas facilitan la comprensión de las tendencias de su rendimiento en comparación con la lectura de archivos de texto sin procesar.",
        report_weaknesses_title: "Desafíos",
        report_weakness1: "<strong>Sin Función HUD en Tiempo Real:</strong> A diferencia de los programas profesionales, no puede mostrar las estadísticas del oponente en la mesa en tiempo real.",
        report_weakness2: "<strong>Requiere Subida Manual:</strong> Debe exportar manualmente los historiales de manos del cliente de GGPoker y subirlos.",
        report_weakness3: "<strong>Métricas Básicas:</strong> Aunque cubre estadísticas clave, el nivel de detalle es menos granular que las herramientas profesionales (por ejemplo, no hay análisis de ganancias por manos específicas).",
        report_weakness4: "<strong>Cuello de Botella en el Rendimiento del Frontend:</strong> Con cientos de miles de manos, el cálculo de JavaScript del lado del cliente puede ralentizarse o causar que el navegador se congele.",
        report_weakness5: "<strong>Sin Función de Análisis de Oponentes:</strong> La herramienta se enfoca completamente en los datos del 'Héroe' y no construye una base de datos para analizar oponentes específicos.",
        report_future_title: "Hoja de Ruta Futura",
        report_future1: "<strong>Integración de Backend en la Nube:</strong> Mover las tareas de cálculo intensivo a un servicio de backend para resolver los problemas de rendimiento del frontend.",
        report_future2: "<strong>Cuentas de Usuario y Sincronización de Datos:</strong> Introducir cuentas de usuario para guardar automáticamente los resultados del análisis en la nube, permitiendo la sincronización de datos entre dispositivos.",
        report_future3: "<strong>Replay Visual de Manos:</strong> Agregar una función para reproducir gráficamente una mano seleccionada de principio a fin.",
        report_future4: "<strong>Filtros de Datos Avanzados:</strong> Permitir a los usuarios filtrar datos por posición, manos iniciales, tamaño del bote y más para un análisis más profundo.",
        report_future5: "<strong>Mapa de Calor de la Matriz de Manos Iniciales:</strong> Mostrar datos de VPIP, PFR y ganancias para todas las manos iniciales en una cuadrícula de 13x13.",
        report_future6: "<strong>Análisis de Partidas/Niveles Específicos:</strong> Agregar filtros para analizar solo niveles de ciegas o tipos de juego específicos (ej. Rush & Cash).",
        report_future7: "<strong>Más Tipos de Gráficos:</strong> Introducir gráficos de pastel (distribución de acciones) y gráficos de radar (para una vista holística del estilo de un jugador).",
        report_future8: "<strong>Etiquetado Simple de Oponentes:</strong> Aunque no es un HUD completo, permitir a los usuarios agregar etiquetas (ej. Fish, TAG) a los ID de los oponentes durante la revisión.",
        report_future9: "<strong>Módulos de Aprendizaje Orientados a Objetivos:</strong> Recomendar recursos de aprendizaje de póker relevantes basados en las debilidades estadísticas identificadas.",
        report_future10: "<strong>Informes Compartibles:</strong> Generar un enlace compartible y de solo lectura a una página de informe (excluyendo detalles sensibles) para discusiones con entrenadores o amigos.",
    },
};


let currentLanguage = 'en';

export function setLanguage(lang) {
    return new Promise((resolve) => {
        if (translations[lang]) {
            currentLanguage = lang;
        } else {
            currentLanguage = 'en'; // Fallback to English
        }
        localStorage.setItem('language', currentLanguage);
        updateUIText();
        resolve();
    });
}


export function getLang(key, fallback = '') {
    return translations[currentLanguage]?.[key] || translations.en?.[key] || fallback || key;
}

export function updateUIText() {
    document.querySelectorAll('[data-lang]').forEach(element => {
        const key = element.getAttribute('data-lang');
        const translation = getLang(key);
        if (translation) {
             // Handle specific elements like title
            if (element.tagName === 'TITLE') {
                element.textContent = translation;
            } else {
                 element.innerHTML = translation;
            }
        }
    });
    document.querySelectorAll('[data-lang-tab]').forEach(element => {
        const key = element.getAttribute('data-lang-tab');
        element.textContent = getLang(key);
    });
}
